### ISSUE TITLE
非常有用的模块，建议提交至lsposed仓库

### ISSUE THREAD

**Issue by Marukon** [AoEiuV020/IAmNotDisabled#1]
这个模块非常好用。谢谢作者！
建议作者提交至lsposed仓库（https://github.com/Xposed-Modules-Repo/submission ）， 方便更多人发现这么好用的模块。

**Comment by AoEiuV020** [comment]
嗯，有打算，自己先用着抽空了解一下模块发布就发出来，

**Comment by AoEiuV020** [comment]
OK了，提交到仓库了，
https://modules.lsposed.org/module/cc.aoeiuv020.iamnotdisabled.hook
