### ISSUE TITLE
被hook的APP會閃退

### ISSUE THREAD

**Issue by Sssrrr0227** [AoEiuV020/IAmNotDisabled#10]
android 13
使用版本6.5如標題

**Comment by AoEiuV020** [comment]
是什么app， 
！！！本项目并非反反作弊用途，只针对善意的无障碍检测，不保证对反作弊检测有效！！！

**Comment by Sssrrr0227** [comment]
Google和Gboard及測試軟體都會閃退也只有開scene而已

**Comment by AoEiuV020** [comment]
我刚试了下谷歌市场新下载的 gboard 13.6.11.574113912-release-arm64-v8a  , 没有出现闪退之类的，
google指的是com.google.android.googlequicksearchbox吗？刚下载了个14.49.40.28.arm64没有问题，
不过我不了解这些app隐藏无障碍是有什么作用？

另外我这边的xposed是 magisk 25.2 zygisk + lsposed 1.8.6, 其他xposed环境包括无root的hook注入我不了解，

**Comment by Sssrrr0227** [comment]
Google不隱藏無障礙Google助手會不一樣(如圖
![Screenshot_2023-12-19-16-45-22-059_com google android googlequicksearchbox](https://github.com/AoEiuV020/IAmNotDisabled/assets/62554394/312b7ec7-9b0d-445d-a0b0-5bc21735eac8)
![Screenshot_2023-12-19-16-37-11-786_cc aoeiuv020 iamnotdisabled](https://github.com/AoEiuV020/IAmNotDisabled/assets/62554394/4f2301e3-79fe-4f8a-8ab0-0954af052d29)

**Comment by Sssrrr0227** [comment]
解決了 lsp降到1.8.6就沒問題了
