### ISSUE TITLE
LSPosed仓库无法检测到6.6版本更新

### ISSUE THREAD

**Issue by SpeedPartner** [AoEiuV020/IAmNotDisabled#12]
一直还是显示6.5版本

**Comment by AoEiuV020** [comment]
是的，我也发现了，但是翻来覆去怎么折腾都更新不到那边，不知道咋回事，暂且放弃了，

**Comment by JasonKhew96** [comment]
不知道为什么 tag 有问题，bot 没加上去，换了 tag 好了

https://modules.lsposed.org/module/cc.aoeiuv020.iamnotdisabled.hook/
