### ISSUE TITLE
是否有计划通过Hook System Server全局屏蔽

### ISSUE THREAD

**Issue by Nitsuya** [AoEiuV020/IAmNotDisabled#13]
是否有计划通过Hook System Server全局屏蔽, 并添加黑白名单. 从而绕过Hook应用.

**Comment by AoEiuV020** [comment]
不太明白这样做的好处，

**Comment by Nitsuya** [comment]
不入侵应用侧, 也算是对抗应用检测.

**Comment by AoEiuV020** [comment]
不打算做对抗应用检测，只针对善意的检测，

**Comment by Nitsuya** [comment]
https://github.com/Nitsuya/DoNotTryAccessibility

已重新开坑. 感谢项目提供的Hook点入口.
