### ISSUE TITLE
隐藏xposed和隐藏无障碍服务需求冲突

### ISSUE THREAD

**Issue by luoxuebinfei** [AoEiuV020/IAmNotDisabled#2]
有一些软件检测xposed比检测无障碍服务严格，但hook了该应用后虽然无障碍服务隐藏了，但xposed就隐藏不了了，在这种情况下两者只能取其一，大佬有啥好的方法吗？

**Comment by AoEiuV020** [comment]
有专门用于隐藏的模块，还是隐藏不了的话估计就没有通用的方法，只能针对特定app hook其中的hook检测方法才行了，
实际上我目前并没有hack有检测xposed的app，只做些基本的隐藏，还用不了就不用了，
这种魔高一尺道高一丈的博弈不太想参与，
这个项目IAmNotDisabled针对的也不是反作弊，
