### ISSUE TITLE
zygisk版magisk不能用

### ISSUE THREAD

**Issue by la5-u** [AoEiuV020/IAmNotDisabled#4]
求更新。

**Comment by AoEiuV020** [comment]
无效吗，还是报错了？
虽然开发的时候用的是riru，但我现在使用的就是zygisk-lsposed，啥也没改，直接兼容的，
另外强调一下，我这个不是反反作弊的，不保证隐藏效果的，
而zygisk不能配置排除目标app隐藏magisk，这会导致模块失效，

**Comment by la5-u** [comment]
用软件检测隐藏没生效。
