### ISSUE TITLE
LSPosed-v1.9.0-6990版本上隐藏无障碍会导致无法在被隐藏的应用中使用无障碍

### ISSUE THREAD

**Issue by hlyzhot** [AoEiuV020/IAmNotDisabled#8]
例如，对A应用隐藏无障碍，会导致B应用无法在A应用内使用无障碍功能，无法获取任何控件（节点）

**Comment by AoEiuV020** [comment]
唔，这应该算设计如此，这里不是反反作弊，只针对善意但多余的无障碍识别，实际有真的需要在这A应用使用无障碍就该被A识别到，

**Comment by winlee-d** [comment]
找了两天，刚刚才找到原因，使用非残后隐藏该软件a后，利用无障碍进行操作的软件b就无法在a上进行无障碍操作了，原来源头在lsp这里，我哭了😒😒😒
