### ISSUE TITLE
还会再更新吗，已经不适用于现在的版本了

### ISSUE THREAD

**Issue by winlee-d** [AoEiuV020/IAmNotDisabled#9]
LSPosed-v1.9.0-6990版本上隐藏无障碍会导致无法在被隐藏的应用中使用无障碍，即使用非残后隐藏该软件a后，利用无障碍进行操作的软件b就无法在a上进行无障碍操作了，还有没有更强大的方式，非残隐藏后就会被检测到hook了。

**Comment by AoEiuV020** [comment]
这里不是反反作弊，只针对善意且多余的无障碍检测，隐藏后确实就无法使用无障碍了，
